[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython<3.0",
    "spacy>=4.0.0.dev1,<4.1.0",
    "numpy",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:^.*Skipping device Apple Paravirtual device that does not support Metal 2.0.*",
]
